// Vocabulario para acampar en Japón. Cada palabra: [escritura, lectura en kana, romaji, español, emoji]
const VOCABULARIO = [
  { id: 'equipo', titulo: 'Equipo de acampada', emoji: '🎒', palabras: [
    ['テント', 'てんと', 'tento', 'tienda de campaña', '⛺'],
    ['寝袋', 'ねぶくろ', 'nebukuro', 'saco de dormir', '🛌'],
    ['シュラフ', 'しゅらふ', 'shurafu', 'saco de dormir (jerga campista)', '🛌'],
    ['マット', 'まっと', 'matto', 'esterilla', '🟫'],
    ['ペグ', 'ぺぐ', 'pegu', 'piqueta', '📌'],
    ['ハンマー', 'はんまー', 'hanmā', 'martillo', '🔨'],
    ['ロープ', 'ろーぷ', 'rōpu', 'cuerda', '🪢'],
    ['タープ', 'たーぷ', 'tāpu', 'toldo', '⛱️'],
    ['ランタン', 'らんたん', 'rantan', 'farol', '🏮'],
    ['懐中電灯', 'かいちゅうでんとう', 'kaichū dentō', 'linterna', '🔦'],
    ['ヘッドライト', 'へっどらいと', 'heddoraito', 'linterna frontal', '💡'],
    ['椅子', 'いす', 'isu', 'silla', '🪑'],
    ['机', 'つくえ', 'tsukue', 'mesa', '🪵'],
    ['水筒', 'すいとう', 'suitō', 'cantimplora', '🧴'],
    ['クーラーボックス', 'くーらーぼっくす', 'kūrā bokkusu', 'nevera portátil', '🧊'],
    ['カイロ', 'かいろ', 'kairo', 'calentador de bolsillo', '🔥'],
    ['軍手', 'ぐんて', 'gunte', 'guantes de trabajo', '🧤'],
    ['防寒着', 'ぼうかんぎ', 'bōkangi', 'ropa de abrigo', '🧥'],
    ['雨具', 'あまぐ', 'amagu', 'ropa de lluvia', '☔'],
    ['地図', 'ちず', 'chizu', 'mapa', '🗺️'],
    ['リュック', 'りゅっく', 'ryukku', 'mochila', '🎒'],
    ['電池', 'でんち', 'denchi', 'pila', '🔋'],
  ]},
  { id: 'fuego', titulo: 'Fuego y cocina', emoji: '🔥', palabras: [
    ['焚き火', 'たきび', 'takibi', 'hoguera', '🔥'],
    ['焚き火台', 'たきびだい', 'takibidai', 'brasero para hoguera', '🔥'],
    ['薪', 'まき', 'maki', 'leña', '🪵'],
    ['炭', 'すみ', 'sumi', 'carbón vegetal', '⚫'],
    ['着火剤', 'ちゃっかざい', 'chakkazai', 'pastilla de encendido', '🧨'],
    ['火', 'ひ', 'hi', 'fuego', '🔥'],
    ['煙', 'けむり', 'kemuri', 'humo', '💨'],
    ['灰', 'はい', 'hai', 'ceniza', '🩶'],
    ['鍋', 'なべ', 'nabe', 'olla / guiso caliente', '🍲'],
    ['フライパン', 'ふらいぱん', 'furaipan', 'sartén', '🍳'],
    ['バーナー', 'ばーなー', 'bānā', 'hornillo', '🔥'],
    ['ガス缶', 'がすかん', 'gasukan', 'cartucho de gas', '🥫'],
    ['お湯', 'おゆ', 'oyu', 'agua caliente', '♨️'],
    ['沸かす', 'わかす', 'wakasu', 'hervir (agua)', '🫖'],
    ['焼く', 'やく', 'yaku', 'asar', '🍢'],
    ['煮る', 'にる', 'niru', 'guisar / cocer', '🍲'],
    ['包丁', 'ほうちょう', 'hōchō', 'cuchillo de cocina', '🔪'],
    ['まな板', 'まないた', 'manaita', 'tabla de cortar', '🟫'],
    ['割り箸', 'わりばし', 'waribashi', 'palillos desechables', '🥢'],
    ['カップ麺', 'かっぷめん', 'kappu men', 'fideos instantáneos', '🍜'],
    ['おにぎり', 'おにぎり', 'onigiri', 'bola de arroz', '🍙'],
    ['コーヒー', 'こーひー', 'kōhī', 'café', '☕'],
    ['いただきます', 'いただきます', 'itadakimasu', '«que aproveche» (antes de comer)', '🙏'],
    ['ごちそうさま', 'ごちそうさま', 'gochisōsama', '«gracias por la comida» (después)', '😋'],
    ['おいしい', 'おいしい', 'oishii', 'rico, delicioso', '😋'],
  ]},
  { id: 'camping', titulo: 'En el camping', emoji: '🏕️', palabras: [
    ['キャンプ場', 'きゃんぷじょう', 'kyanpujō', 'camping (el lugar)', '🏕️'],
    ['受付', 'うけつけ', 'uketsuke', 'recepción', '🛎️'],
    ['管理棟', 'かんりとう', 'kanritō', 'edificio de administración', '🏠'],
    ['予約', 'よやく', 'yoyaku', 'reserva', '📅'],
    ['予約制', 'よやくせい', 'yoyakusei', 'solo con reserva', '📅'],
    ['料金', 'りょうきん', 'ryōkin', 'tarifa', '💴'],
    ['一泊', 'いっぱく', 'ippaku', 'una noche', '🌙'],
    ['日帰り', 'ひがえり', 'higaeri', 'excursión de un día', '☀️'],
    ['区画サイト', 'くかくさいと', 'kukaku saito', 'parcela delimitada', '🟩'],
    ['フリーサイト', 'ふりーさいと', 'furī saito', 'zona libre (sin parcelas)', '🌾'],
    ['オートキャンプ', 'おーときゃんぷ', 'ōto kyanpu', 'camping con coche al lado', '🚗'],
    ['炊事場', 'すいじば', 'suijiba', 'fregadero / zona de cocina', '🚰'],
    ['トイレ', 'といれ', 'toire', 'baño', '🚻'],
    ['シャワー', 'しゃわー', 'shawā', 'ducha', '🚿'],
    ['ゴミ捨て場', 'ごみすてば', 'gomi suteba', 'punto de basura', '🗑️'],
    ['ゴミは持ち帰り', 'ごみはもちかえり', 'gomi wa mochikaeri', 'llévate tu basura', '♻️'],
    ['直火禁止', 'じかびきんし', 'jikabi kinshi', 'prohibido el fuego en el suelo', '🚫'],
    ['消灯', 'しょうとう', 'shōtō', 'hora de apagar luces', '🌙'],
    ['チェックイン', 'ちぇっくいん', 'chekku in', 'hora de llegada', '🕐'],
    ['チェックアウト', 'ちぇっくあうと', 'chekku auto', 'hora de salida', '🕙'],
    ['売店', 'ばいてん', 'baiten', 'tienda del camping', '🏪'],
    ['薪販売', 'まきはんばい', 'maki hanbai', 'venta de leña', '🪵'],
    ['設営', 'せつえい', 'setsuei', 'montar el campamento', '⛺'],
    ['撤収', 'てっしゅう', 'tesshū', 'desmontar el campamento', '📦'],
    ['ソロキャン', 'そろきゃん', 'soro kyan', 'acampada en solitario', '🧍'],
    ['グルキャン', 'ぐるきゃん', 'guru kyan', 'acampada en grupo', '👯'],
  ]},
  { id: 'naturaleza', titulo: 'Naturaleza y tiempo', emoji: '🌤️', palabras: [
    ['山', 'やま', 'yama', 'montaña', '⛰️'],
    ['富士山', 'ふじさん', 'Fujisan', 'monte Fuji', '🗻'],
    ['湖', 'みずうみ', 'mizuumi', 'lago', '🏞️'],
    ['川', 'かわ', 'kawa', 'río', '💧'],
    ['海', 'うみ', 'umi', 'mar', '🌊'],
    ['森', 'もり', 'mori', 'bosque', '🌲'],
    ['滝', 'たき', 'taki', 'cascada', '💦'],
    ['岬', 'みさき', 'misaki', 'cabo', '🪨'],
    ['高原', 'こうげん', 'kōgen', 'meseta', '🌾'],
    ['星', 'ほし', 'hoshi', 'estrella', '⭐'],
    ['月', 'つき', 'tsuki', 'luna', '🌙'],
    ['空', 'そら', 'sora', 'cielo', '🌌'],
    ['雲海', 'うんかい', 'unkai', 'mar de nubes', '☁️'],
    ['日の出', 'ひので', 'hinode', 'amanecer', '🌅'],
    ['夕日', 'ゆうひ', 'yūhi', 'sol del atardecer', '🌇'],
    ['紅葉', 'こうよう', 'kōyō', 'hojas rojas de otoño', '🍁'],
    ['桜', 'さくら', 'sakura', 'cerezo en flor', '🌸'],
    ['雪', 'ゆき', 'yuki', 'nieve', '❄️'],
    ['霜', 'しも', 'shimo', 'escarcha', '🧊'],
    ['風', 'かぜ', 'kaze', 'viento', '🌬️'],
    ['雨', 'あめ', 'ame', 'lluvia', '🌧️'],
    ['晴れ', 'はれ', 'hare', 'soleado', '☀️'],
    ['曇り', 'くもり', 'kumori', 'nublado', '☁️'],
    ['天気予報', 'てんきよほう', 'tenki yohō', 'previsión del tiempo', '📺'],
    ['気温', 'きおん', 'kion', 'temperatura', '🌡️'],
    ['寒い', 'さむい', 'samui', 'hace frío', '🥶'],
    ['暖かい', 'あたたかい', 'atatakai', 'templado, cálido', '😊'],
    ['熊', 'くま', 'kuma', 'oso', '🐻'],
    ['鹿', 'しか', 'shika', 'ciervo', '🦌'],
    ['虫', 'むし', 'mushi', 'insecto', '🐛'],
  ]},
  { id: 'carretera', titulo: 'Carretera y señales', emoji: '🚗', palabras: [
    ['道', 'みち', 'michi', 'camino', '🛣️'],
    ['国道', 'こくどう', 'kokudō', 'carretera nacional', '🛣️'],
    ['県道', 'けんどう', 'kendō', 'carretera provincial', '🛤️'],
    ['高速道路', 'こうそくどうろ', 'kōsoku dōro', 'autopista', '🛣️'],
    ['峠', 'とうげ', 'tōge', 'puerto de montaña', '⛰️'],
    ['トンネル', 'とんねる', 'tonneru', 'túnel', '🚇'],
    ['橋', 'はし', 'hashi', 'puente', '🌉'],
    ['吊り橋', 'つりばし', 'tsuribashi', 'puente colgante', '🌁'],
    ['交差点', 'こうさてん', 'kōsaten', 'cruce', '✳️'],
    ['信号', 'しんごう', 'shingō', 'semáforo', '🚦'],
    ['止まれ', 'とまれ', 'tomare', 'STOP (alto)', '🛑'],
    ['徐行', 'じょこう', 'jokō', 'circule despacio', '🐢'],
    ['一方通行', 'いっぽうつうこう', 'ippō tsūkō', 'sentido único', '⬆️'],
    ['通行止め', 'つうこうどめ', 'tsūkōdome', 'carretera cortada', '⛔'],
    ['冬季閉鎖', 'とうきへいさ', 'tōki heisa', 'cerrado en invierno', '❄️'],
    ['迂回路', 'うかいろ', 'ukairo', 'desvío', '↪️'],
    ['工事中', 'こうじちゅう', 'kōjichū', 'en obras', '🚧'],
    ['落石注意', 'らくせきちゅうい', 'rakuseki chūi', 'cuidado: caída de piedras', '🪨'],
    ['凍結注意', 'とうけつちゅうい', 'tōketsu chūi', 'cuidado: hielo', '🧊'],
    ['チェーン規制', 'ちぇーんきせい', 'chēn kisei', 'cadenas obligatorias', '⛓️'],
    ['渋滞', 'じゅうたい', 'jūtai', 'atasco', '🚗'],
    ['駐車場', 'ちゅうしゃじょう', 'chūshajō', 'aparcamiento', '🅿️'],
    ['ガソリンスタンド', 'がそりんすたんど', 'gasorin sutando', 'gasolinera', '⛽'],
    ['満タン', 'まんたん', 'mantan', 'depósito lleno', '⛽'],
    ['道の駅', 'みちのえき', 'michi no eki', 'área de descanso con tienda local', '🏬'],
    ['サービスエリア', 'さーびすえりあ', 'sābisu eria', 'área de servicio (autopista)', '🍱'],
    ['原付', 'げんつき', 'gentsuki', 'ciclomotor (el de Rin)', '🛵'],
    ['バイク', 'ばいく', 'baiku', 'moto', '🏍️'],
    ['自転車', 'じてんしゃ', 'jitensha', 'bicicleta', '🚲'],
    ['ヘルメット', 'へるめっと', 'herumetto', 'casco', '⛑️'],
  ]},
  { id: 'gps', titulo: 'GPS y navegador', emoji: '🧭', palabras: [
    ['カーナビ', 'かーなび', 'kānabi', 'navegador del coche', '🧭'],
    ['現在地', 'げんざいち', 'genzaichi', 'ubicación actual', '📍'],
    ['目的地', 'もくてきち', 'mokutekichi', 'destino', '🏁'],
    ['経由地', 'けいゆち', 'keiyuchi', 'parada intermedia', '📌'],
    ['右折', 'うせつ', 'usetsu', 'girar a la derecha', '➡️'],
    ['左折', 'させつ', 'sasetsu', 'girar a la izquierda', '⬅️'],
    ['直進', 'ちょくしん', 'chokushin', 'seguir recto', '⬆️'],
    ['Uターン', 'ゆーたーん', 'yū tān', 'cambio de sentido', '↩️'],
    ['北', 'きた', 'kita', 'norte', '⬆️'],
    ['南', 'みなみ', 'minami', 'sur', '⬇️'],
    ['東', 'ひがし', 'higashi', 'este', '➡️'],
    ['西', 'にし', 'nishi', 'oeste', '⬅️'],
    ['300メートル先、左方向です', 'さんびゃくめーとるさき、ひだりほうこうです', 'sanbyaku mētoru saki, hidari hōkō desu', 'en 300 metros, a la izquierda', '⬅️'],
    ['まもなく右方向です', 'まもなくみぎほうこうです', 'mamonaku migi hōkō desu', 'enseguida, a la derecha', '➡️'],
    ['この先、道なりです', 'このさき、みちなりです', 'kono saki, michinari desu', 'siga la carretera', '⬆️'],
    ['ルートを再検索します', 'るーとをさいけんさくします', 'rūto o saikensaku shimasu', 'recalculando la ruta', '🔄'],
    ['目的地周辺です', 'もくてきちしゅうへんです', 'mokutekichi shūhen desu', 'ha llegado a las inmediaciones del destino', '📍'],
    ['目的地に到着しました', 'もくてきちにとうちゃくしました', 'mokutekichi ni tōchaku shimashita', 'ha llegado a su destino', '🏁'],
    ['この先、事故多発地点です', 'このさき、じこたはつちてんです', 'kono saki, jiko tahatsu chiten desu', 'más adelante, punto con muchos accidentes', '⚠️'],
    ['電波が届きません', 'でんぱがとどきません', 'denpa ga todokimasen', 'no hay cobertura', '📵'],
  ]},
  { id: 'sitios', titulo: 'Sitios y viaje', emoji: '🗾', palabras: [
    ['駅', 'えき', 'eki', 'estación', '🚉'],
    ['バス停', 'ばすてい', 'basutei', 'parada de autobús', '🚏'],
    ['切符', 'きっぷ', 'kippu', 'billete', '🎫'],
    ['温泉', 'おんせん', 'onsen', 'aguas termales', '♨️'],
    ['露天風呂', 'ろてんぶろ', 'rotenburo', 'baño termal al aire libre', '♨️'],
    ['コンビニ', 'こんびに', 'konbini', 'tienda 24 h', '🏪'],
    ['スーパー', 'すーぱー', 'sūpā', 'supermercado', '🛒'],
    ['神社', 'じんじゃ', 'jinja', 'santuario sintoísta', '⛩️'],
    ['お寺', 'おてら', 'otera', 'templo budista', '🛕'],
    ['展望台', 'てんぼうだい', 'tenbōdai', 'mirador', '🔭'],
    ['観光案内所', 'かんこうあんないじょ', 'kankō annaijo', 'oficina de turismo', 'ℹ️'],
    ['ロープウェイ', 'ろーぷうぇい', 'rōpuwei', 'teleférico', '🚡'],
    ['登山口', 'とざんぐち', 'tozanguchi', 'inicio de la ruta de montaña', '🥾'],
    ['入口', 'いりぐち', 'iriguchi', 'entrada', '🚪'],
    ['出口', 'でぐち', 'deguchi', 'salida', '🚪'],
    ['お土産', 'おみやげ', 'omiyage', 'recuerdo / regalo de viaje', '🎁'],
    ['営業時間', 'えいぎょうじかん', 'eigyō jikan', 'horario de apertura', '🕘'],
    ['定休日', 'ていきゅうび', 'teikyūbi', 'día de cierre', '📅'],
  ]},
  { id: 'frases', titulo: 'Frases para el camping', emoji: '💬', palabras: [
    ['今日、泊まれますか？', 'きょう、とまれますか？', 'kyō, tomaremasu ka?', '¿Puedo quedarme esta noche?', '⛺'],
    ['予約しています', 'よやくしています', 'yoyaku shite imasu', 'Tengo reserva', '📅'],
    ['一泊いくらですか？', 'いっぱくいくらですか？', 'ippaku ikura desu ka?', '¿Cuánto cuesta una noche?', '💴'],
    ['薪はどこで買えますか？', 'まきはどこでかえますか？', 'maki wa doko de kaemasu ka?', '¿Dónde puedo comprar leña?', '🪵'],
    ['ゴミはどこに捨てますか？', 'ごみはどこにすてますか？', 'gomi wa doko ni sutemasu ka?', '¿Dónde tiro la basura?', '🗑️'],
    ['焚き火をしてもいいですか？', 'たきびをしてもいいですか？', 'takibi o shite mo ii desu ka?', '¿Puedo hacer hoguera?', '🔥'],
    ['トイレはどこですか？', 'といれはどこですか？', 'toire wa doko desu ka?', '¿Dónde está el baño?', '🚻'],
    ['富士山が見えますか？', 'ふじさんがみえますか？', 'Fujisan ga miemasu ka?', '¿Se ve el Fuji?', '🗻'],
    ['道に迷いました', 'みちにまよいました', 'michi ni mayoimashita', 'Me he perdido', '😵'],
    ['この道は通れますか？', 'このみちはとおれますか？', 'kono michi wa tooremasu ka?', '¿Se puede pasar por esta carretera?', '🛣️'],
    ['一緒に食べませんか？', 'いっしょにたべませんか？', 'issho ni tabemasen ka?', '¿Comemos juntos?', '🍲'],
    ['寒っ！', 'さむっ！', 'samu!', '¡Qué frío! (coloquial)', '🥶'],
    ['お疲れさまです', 'おつかれさまです', 'otsukaresama desu', 'buen trabajo / saludo tras el esfuerzo', '🙇'],
    ['よろしくお願いします', 'よろしくおねがいします', 'yoroshiku onegai shimasu', 'encantado / cuento contigo', '🤝'],
  ]},
  { id: 'anime', titulo: 'Palabras de Yuru Camp', emoji: '🎬', palabras: [
    ['ゆるキャン', 'ゆるきゃん', 'yuru kyan', 'acampada relajada (el título)', '😌'],
    ['へやキャン', 'へやきゃん', 'heya kyan', 'acampar en la habitación (el club)', '🏠'],
    ['野クル', 'のくる', 'nokuru', 'club de actividades al aire libre', '🏕️'],
    ['野外活動サークル', 'やがいかつどうさーくる', 'yagai katsudō sākuru', 'nombre completo del club', '🏕️'],
    ['部室', 'ぶしつ', 'bushitsu', 'sala del club', '🚪'],
    ['顧問', 'こもん', 'komon', 'profesor responsable del club', '🧑‍🏫'],
    ['先輩', 'せんぱい', 'senpai', 'compañero veterano', '🧑‍🎓'],
    ['カレーめん', 'かれーめん', 'karē men', 'fideos de curry (los de Rin)', '🍜'],
    ['めしテロ', 'めしてろ', 'meshi tero', '«terrorismo gastronómico» (fotos de comida que dan hambre)', '🤤'],
    ['ほうとう', 'ほうとう', 'hōtō', 'fideos gruesos de Yamanashi', '🍲'],
    ['富士宮やきそば', 'ふじのみややきそば', 'Fujinomiya yakisoba', 'fideos salteados de Fujinomiya', '🍝'],
    ['身延まんじゅう', 'みのぶまんじゅう', 'Minobu manjū', 'bollito dulce de Minobu', '🥮'],
    ['バイト', 'ばいと', 'baito', 'trabajo a tiempo parcial', '💼'],
    ['ちくわ', 'ちくわ', 'chikuwa', 'el perro de Ena (y un pastel de pescado)', '🐶'],
    ['〜ずら', 'ずら', '~zura', 'coletilla del dialecto de Yamanashi y Shizuoka (≈ «¿verdad?»)', '🗣️'],
  ]},
];
